// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx6JW4d-hxpxaaNdVljjArtoXJu6vPayM',
    appId: '1:258944101244:web:9e214aa07b919711a392f9',
    messagingSenderId: '258944101244',
    projectId: 'canvas-connect-5e3c9',
    authDomain: 'canvas-connect-5e3c9.firebaseapp.com',
    storageBucket: 'canvas-connect-5e3c9.appspot.com',
    measurementId: 'G-1SRLH04G7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ep0GChlIpSWM6pJtM_RXXb-almlt8kQ',
    appId: '1:258944101244:android:4038091bec5cc911a392f9',
    messagingSenderId: '258944101244',
    projectId: 'canvas-connect-5e3c9',
    storageBucket: 'canvas-connect-5e3c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6COhznqOBN_8iJeJiQrThpZkvLO7KYsw',
    appId: '1:258944101244:ios:ed27ed487a95dd78a392f9',
    messagingSenderId: '258944101244',
    projectId: 'canvas-connect-5e3c9',
    storageBucket: 'canvas-connect-5e3c9.appspot.com',
    iosClientId: '258944101244-kvln9ca1hts0kmbpg465iv8rmck3q6sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.canvasConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6COhznqOBN_8iJeJiQrThpZkvLO7KYsw',
    appId: '1:258944101244:ios:ed27ed487a95dd78a392f9',
    messagingSenderId: '258944101244',
    projectId: 'canvas-connect-5e3c9',
    storageBucket: 'canvas-connect-5e3c9.appspot.com',
    iosClientId: '258944101244-kvln9ca1hts0kmbpg465iv8rmck3q6sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.canvasConnect',
  );
}
